# Generated by Django 5.1 on 2024-09-02 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowedsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=125)),
                ('author', models.CharField(max_length=255)),
                ('allowedsub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.allowedsub')),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.review')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.tag')),
            ],
        ),
    ]
