# Generated by Django 5.1 on 2024-09-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_sub_allowedsub_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='Book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
            preserve_default=False,
        ),
    ]
