# Generated by Django 5.1 on 2024-09-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_review_id_review_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='allowedsub_id',
        ),
        migrations.AddField(
            model_name='book',
            name='sub_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.sub'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Allowedsub',
        ),
    ]
